<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <title>Химия</title>
    <link rel="stylesheet" type="text/css" href="http://scienchemistry.org/web/CSS/style.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@700&family=Rubik+Mono+One&family=Bad+Script&family=Jura:wght@300&family=Balsamiq+Sans:ital@1&display=swap" rel="stylesheet">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script> 
</head>
<body>        
    <div class="wrapper">
        <!--#include virtual="/web/Sitedesign/Menu.html"-->
        <div class="container2">
            <!--#include virtual="/web/Sitedesign/Tablestructure.html"-->
        </div>
        <div class="container">
            <div class="information"  id="P">
                <h1 class="elements">Фосфор</h1>
                <hr>
                <div class='t'>
                    <table class='infobox'>
                        <tbody>
                            <tr>
                                <th class='plainlist' colspan="2">Химические элементы</th>
                            </tr>
                            <tr>
                                <th class='definition' colspan="2" style="background: #1b1e20;color:#53ee61;">P</th>
                            </tr>
                            <tr>
                                <th colspan="2">
                                    <img class="E-img" src="http://chemistry.com/Elements/Image/Nonmetals/P/P.gif">
                                </th>
                            </tr>
                            <tr>
                                <th class='plainlist'>Предмет изучения</th>
                                <td class='definition' style="color:#53ee61;">Химия</td>
                            </tr>
                            <tr>
                                <th class='plainlist'>Период  зарождения</th>
                                <td class='definition' style="color:#53ee61;">1669 г.</td>
                            </tr>
                            <tr>
                                <th class='plainlist'>Используется в</th>
                                <td class='definition' style="color:#53ee61;">производстве спичек, взрывчатых веществ; топливо</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <p class="font-p"><strong class="preface">Фосфор</strong> - это химический элемент 15-й группы (по устаревшей классификации — главной подгруппы пятой группы) третьего периода периодической системы <a href="http://www.scienchemistry.org/web/HistoricalFigures/Mendeleev.html" class="mini-preview-anchor">Д.И.Менделеева<span class="mini-preview-wrapper" style="width: 320px; height: 490px; top: -498px;"><span class="mini-preview-loading" style="height: 478px;"><img class="mini-preview-img" src="http://chemistry.com/HistoricalFigures/Mendeleev/img.jpg"><span class="p"><strong class="word">Д.И.Менделеев</strong> — русский учёный-энциклопедист: химик, физикохимик, физик и так далее. Среди самых известных открытий — периодический закон химических элементов, один из фундаментальных законов мироздания, неотъемлемый для всего естествознания.</span></span></span></a>; имеет атомный номер 15. Элемент входит в группу пниктогенов. Фосфор — один из распространённых элементов земной коры: его содержание составляет 0,08—0,09 % её массы. Концентрация в морской воде 0,07 мг/л. В свободном состоянии не встречается из-за высокой химической активности. Образует около 190 минералов, важнейшими из которых являются апатит Ca<sub>5</sub> (PO<sub>4</sub> )<sub>3</sub> (F,Cl,OH), фосфорит (Сa<sub>3</sub> (PO<sub>4</sub> )<sub>2</sub> ) и другие. Фосфор входит в состав важнейших биологических соединений — фосфолипидов. Содержится в животных тканях, входит в состав белков и других важнейших органических соединений (АТФ, ДНК), является элементом жизни.</p>
                <h2 class="elements">Физические свойства</h2>
                <div class="thumb-tright">
                    <div class="thumbinner" style="width:502px;">
                        <img alt="P2"  src="http://chemistry.com/Elements/Image/Nonmetals/P/P2.jpg" style="width:500px;"> 
                        <div class="thumbcaption">
                            <p class="font-p" style="margin:0;font-size:16px;">Аллотропные модификации фосфора (жёлтый, 2 образца красного, фиолетовый)</p>
                        </div>
                    </div> 
                </div>
                <p class="font-p">Элементарный фосфор при нормальных условиях существует в виде нескольких устойчивых аллотропных модификаций. Все существующие аллотропные модификации фосфора пока (2016 г.) до конца не изучены. Традиционно различают три его модификации: белый, красный, чёрный. Иногда их ещё называют главными аллотропными модификациями, подразумевая при этом, что все остальные описываемые модификации являются смесью этих трёх. При стандартных условиях устойчивы только три аллотропических модификации фосфора, например, белый фосфор термодинамически неустойчив (квазистационарное состояние) и переходит со временем при нормальных условиях в красный фосфор. Все модификации различаются по цвету, плотности и другим физическим и химическим характеристикам, особенно по химической активности. При переходе состояния вещества в более термодинамически устойчивую модификацию снижается химическая активность, например, при последовательном превращении белого фосфора в красный, потом красного в чёрный.</p>
                <h3>Белый фосфор</h3>
                <p class="font-p">Белый фосфор представляет собой белое вещество (из-за примесей может иметь желтоватый оттенок). По внешнему виду он очень похож на очищенный воск или парафин, легко режется ножом и деформируется от небольших усилий.</p>
                <p class="font-p">Белый фосфор имеет молекулярную кристаллическую решётку, формула молекулы белого фосфора — P<sub>4</sub> , причём атомы расположены в вершинах тетраэдра. Отливаемый в инертной атмосфере в виде палочек (слитков), он сохраняется в отсутствии воздуха под слоем очищенной воды или в специальных инертных средах.</p>
                <div class="thumb-tright">
                    <div class="thumbinner" style="width:222px;">
                        <img alt="P3"  src="http://chemistry.com/Elements/Image/Nonmetals/P/P3.jpg" style="width:220px;"> 
                        <div class="thumbcaption">
                            <p class="font-p" style="margin:0;font-size:16px;">Молекула белого фосфора</p>
                        </div>
                    </div> 
                </div>
                <p class="font-p">Плохо растворяется в воде, но легкорастворим в органических растворителях. Растворимостью белого фосфора в сероуглероде пользуются для промышленной очистки его от примесей. Плотность белого фосфора из всех его модификаций наименьшая и составляет около 1823 кг/м³. Плавится белый фосфор при 44,1 °C. В парообразном состоянии происходит диссоциация молекул фосфора.</p>
                <p class="font-p">Химически белый фосфор чрезвычайно активен. Например, он медленно окисляется <a href="http://www.scienchemistry.org/web/HTML/O.html" class="mini-preview-anchor">кислородом<span class="mini-preview-wrapper" style="width: 320px; height: 458px; top: -462px;"><span class="mini-preview-loading" style="height: 446px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/Nonmetals/O/O.jpg"><span class="p"><strong class="word">Кислород</strong> — химический элемент 16-й группы, второго периода периодической системы, с атомным номером 8.Кислород — химически активный неметалл, является самым лёгким элементом из группы халькогенов.</span></span></span></a> воздуха уже при комнатной температуре и светится (бледно-зелёное свечение). Явление такого рода свечения вследствие химических реакций окисления называется хемилюминесценцией (иногда ошибочно фосфоресценцией). При взаимодействии с кислородом белый фосфор горит даже под водой.</p>
                <p class="font-p">Белый фосфор не только активен химически, но и весьма ядовит: летальная доза белого фосфора для взрослого человека составляет 0,05—0,15 г, а при хроническом отравлении поражает кости, например, вызывает омертвение челюстей. При контакте с кожей легко самовоспламеняется, вызывая серьёзные ожоги.</p>
                <p class="font-p">Под действием света, при нагревании до не очень высоких температур в безвоздушной среде, а также под действием ионизирующего излучения белый фосфор превращается в красный фосфор.</p>
                <h3>Жёлтый фосфор</h3>
                <p class="font-p">Неочищенный белый фосфор обычно называют «жёлтый фосфор». Сильно ядовитое (ПДК в атмосферном воздухе 0,0005 мг/м³), огнеопасное кристаллическое вещество от светло-жёлтого до тёмно-бурого цвета. Плотность 1,83 г/см³, плавится при 43,1 °C, кипит при +280 °C. В воде не растворяется, на воздухе легко окисляется и самовоспламеняется. Горит ослепительным ярко-зелёным пламенем с выделением густого белого дыма — мелких частичек декаоксида тетрафосфора P<sub>4</sub>O<sub>10</sub> .</p>
                <p class="font-p">Так как фосфор реагирует с водой лишь при температуре свыше 500 °C, то для тушения фосфора используют воду в больших количествах (для снижения температуры очага возгорания и перевода фосфора в твёрдое состояние) или раствор сульфата <a href="http://www.scienchemistry.org/web/HTML/Cu.html" class="mini-preview-anchor">меди<span class="mini-preview-wrapper" style="width: 320px; height: 497px; top: -501px; left: -10px;"><span class="mini-preview-loading" style="height: 485px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/metals/nine_row/Cu/Cu.jpg"><span class="p"><strong class="word">Медь</strong> — химический элемент 11-й группы, четвёртого периода периодической системы, с атомным номером 29. Простое вещество медь — это пластичный переходный металл золотисто-розового цвета. C давних пор широко используется человеком.</span></span></span></a> (медного купороса), после гашения фосфор засыпают влажным песком. Для предохранения от самовозгорания жёлтый фосфор хранится и перевозится под слоем воды (раствора хлорида <a href="http://www.scienchemistry.org/web/HTML/Ca.html" class="mini-preview-anchor">кальция<span class="mini-preview-wrapper" style="width: 320px; height: 434px; top: -438px; left: -10px;"><span class="mini-preview-loading" style="height: 422px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/metals/second_group/Ca/Ca.jpg"><span class="p"><strong class="word">Кальций</strong> — элемент второй группы, четвёртого периода, с атомным номером 20. Простое вещество кальций — мягкий, химически активный щёлочноземельный металл серебристо-белого цвета. Впервые получен в чистом виде Г. Дэви в 1808 году.</span></span></span></a>).</p>
                <h3>Красный фосфор</h3>
                <div class="thumb-tright">
                    <div class="thumbinner" style="width:222px;">
                        <img alt="P4"  src="http://chemistry.com/Elements/Image/Nonmetals/P/P4.jpg" style="width:220px;"> 
                        <div class="thumbcaption">
                            <p class="font-p" style="margin:0;font-size:16px;">Красный фосфор</p>
                        </div>
                    </div> 
                </div>
                <p class="font-p">Красный фосфор — это более термодинамически стабильная модификация элементарного фосфора. Впервые он был получен в 1847 году в Швеции австрийским химиком А. Шрёттером при нагревании белого фосфора при 500 °С в атмосфере угарного газа (СО) в запаянной стеклянной ампуле.</p>
                <p class="font-p">Красный фосфор имеет формулу Р<sub>n</sub> и представляет собой полимер со сложной структурой. В зависимости от способа получения и степени дробления, красный фосфор имеет оттенки от пурпурно-красного до фиолетового, а в литом состоянии — тёмно-фиолетовый с медным оттенком, имеет металлический блеск. Химическая активность красного фосфора значительно ниже, чем у белого; ему присуща исключительно малая растворимость. Растворить красный фосфор возможно лишь в некоторых расплавленных металлах (<a href="http://www.scienchemistry.org/web/HTML/Pb.html" class="mini-preview-anchor">свинец<span class="mini-preview-wrapper" style="width: 320px; height: 503px; top: -507px;"><span class="mini-preview-loading" style="height: 491px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/Post.metals/Pb/Pb.jpg"><span class="p"><strong class="word">Свинец</strong> — элемент 4-й группы, шестого периода периодической системы химических элементов Д. И. Менделеева, с атомным номером 82 и, таким образом, содержит магическое число протонов. Простое вещество свинец — ковкий, сравнительно легкоплавкий тяжёлый металл серебристо-белого цвета с синеватым отливом, токсичен.</span></span></span></a> и <a href="http://www.scienchemistry.org/web/HTML/Bi.html" class="mini-preview-anchor">висмут<span class="mini-preview-wrapper" style="width: 320px; height: 487px; top: -491px;"><span class="mini-preview-loading" style="height: 475px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/Post.metals/Bi/Bi.jpg"><span class="p"><strong class="word">Висмут</strong> — химический элемент с атомным номером 83. Принадлежит к 15-й группе периодической таблицы химических элементов, находится в шестом периоде таблицы. Простое вещество висмут представляет собой при нормальных условиях блестящий серебристый с розоватым оттенком металл.</span></span></span></a>), чем иногда пользуются для получения крупных его кристаллов. Так, например, немецкий физико-химик И. В. Гитторф в 1865 году впервые получил прекрасно построенные, но небольшие по размеру кристаллы (фосфор Гитторфа). Красный фосфор на воздухе не самовоспламеняется, вплоть до температуры 240—250 °С (при переходе в белую форму во время возгонки), но самовоспламеняется при трении или ударе, у него полностью отсутствует явление хемилюминесценции. Нерастворим в воде, а также в бензоле, сероуглероде и других веществах, растворим в трибромиде фосфора. При температуре возгонки красный фосфор превращается в пар, при охлаждении которого образуется в основном белый фосфор.</p>
                <p class="font-p">Ядовитость его в тысячи раз меньше, чем у белого, поэтому он применяется гораздо шире, например, в производстве спичек (составом, в который входит красный фосфор, покрыта тёрочная поверхность спичечных коробков). Плотность красного фосфора также выше, и достигает 2400 кг/м³ в литом виде. При хранении на воздухе красный фосфор в присутствии влаги постепенно окисляется, образуя гигроскопичный оксид, поглощает воду и отсыревает («отмокает»), образуя вязкую фосфорную кислоту; поэтому его хранят в герметичной таре. При «отмокании» — промывают водой от остатков фосфорных кислот, высушивают и используют по назначению.</p>
                <h3>Чёрный фосфор</h3>
                <p class="font-p">Чёрный фосфор — это наиболее стабильная термодинамически и химически наименее активная форма элементарного фосфора. Впервые чёрный фосфор был получен в 1914 году американским физиком П. У. Бриджменом из белого фосфора в виде чёрных блестящих кристаллов, имеющих высокую (2690 кг/м³) плотность. Для проведения синтеза чёрного фосфора Бриджмен применил давление в 2⋅10<sup>9</sup> Па (20 тысяч атмосфер) и температуру около 200 °С. Начало быстрого перехода лежит в области 13 000 атмосфер и температуре около 230 °С.</p>
                <p class="font-p">Чёрный фосфор представляет собой чёрное вещество с металлическим блеском, жирное на ощупь и весьма похожее на графит, и с полностью отсутствующей растворимостью в воде или органических растворителях. Поджечь чёрный фосфор можно, только предварительно сильно раскалив в атмосфере чистого кислорода до 400 °С. Чёрный фосфор проводит электрический ток и имеет свойства полупроводника. Температура плавления чёрного фосфора 1000 °С под давлением 1,8⋅10<sup>6</sup> Па.</p>
                <h2 class="elements">Химические свойства</h2> 
                <p class="font-p">Химическая активность фосфора значительно выше, чем у <a href="http://www.scienchemistry.org/web/HTML/N.html" class="mini-preview-anchor">азота<span class="mini-preview-wrapper" style="width: 320px; height: 435px; top: -439px;"><span class="mini-preview-loading" style="height: 423px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/Nonmetals/N/N.jpg"><span class="p"><strong class="word">Азот</strong> — химический элемент 15-й группы, второго периода периодической системы, с атомным номером 7.Как простое вещество представляет собой двухатомный газ без цвета, вкуса и запаха.Один из самых распространённых элементов на Земле.</span></span></span></a>. Химические свойства фосфора во многом определяются его аллотропной модификацией. Белый фосфор очень активен, в процессе перехода к красному и чёрному фосфору химическая активность снижается. Белый фосфор в воздухе при окислении кислородом воздуха при комнатной температуре излучает видимый свет, свечение обусловлено фотоэмиссионной реакцией окисления фосфора.</p>
                <p class="font-p">В жидком и растворенном состоянии, а также в парах до 800 °С фосфор состоит из молекул P<sub>4</sub> . При нагревании выше 800 °С молекулы диссоциируют:
                    <br><strong>P<sub>4</sub> → 2P<sub>2</sub></strong>
                <br>При температуре выше 2000 °С молекулы распадаются на атомы.</p>
                <h3>Взаимодействие с простыми веществами</h3>
                <p class="font-p">Фосфор легко окисляется <a href="http://www.scienchemistry.org/web/HTML/O.html" class="mini-preview-anchor">кислородом<span class="mini-preview-wrapper" style="width: 320px; height: 458px; top: -462px;"><span class="mini-preview-loading" style="height: 446px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/Nonmetals/O/O.jpg"><span class="p"><strong class="word">Кислород</strong> — химический элемент 16-й группы, второго периода периодической системы, с атомным номером 8.Кислород — химически активный неметалл, является самым лёгким элементом из группы халькогенов.</span></span></span></a>:
                    <br><strong>4P + 5O<sub>2</sub> → 2P<sub>2</sub>O<sub>5</sub></strong> (с избытком кислорода),
                    <br><strong>4P + 3O<sub>2</sub> → 2P<sub>2</sub>O<sub>3</sub></strong> (при медленном окислении или при недостатке кислорода).
                <br>Взаимодействует со многими простыми веществами — галогенами, <a href="http://www.scienchemistry.org/web/HTML/S.html" class="mini-preview-anchor">серой<span class="mini-preview-wrapper" style="width: 320px; height: 504px; top: -508px; left: -10px;"><span class="mini-preview-loading" style="height: 492px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/Nonmetals/S/S.jpg"><span class="p"><strong class="word">Сера</strong> — элемент 6-й группы, 3-го периода периодической системы, с атомным номером 16. В водородных и кислородных соединениях находится в составе различных ионов, образует многие кислоты и соли. Практически нерастворима в воде. Многие серосодержащие соли малорастворимы в воде.</span></span></span></a>, некоторыми металлами, проявляя окислительные и восстановительные свойства.</p>
                <p class="font-p">с металлами — окислитель, образует фосфиды:
                    <br><strong>2P + 3Ca → Ca<sub>3</sub>P<sub>2</sub></strong>
                <br>фосфиды разлагаются водой и кислотами с образованием фосфина.</p>
                <p class="font-p">C неметаллами — восстановитель:
                    <br><strong>2P + 3S → P<sub>2</sub>S<sub>3</sub></strong>
                    <br><strong>2P + 5Cl<sub>2</sub> → 2PCl<sub>5</sub></strong>
                <br>С <a href="http://www.scienchemistry.org/web/HTML/H.html" class="mini-preview-anchor">водородом<span class="mini-preview-wrapper" style="width: 320px; height: 441px; top: -445px;"><span class="mini-preview-loading" style="height: 429px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/Nonmetals/H/H.jpg"><span class="p"><strong class="word">Водород</strong> — химический элемент периодической системы с обозначением H и атомным номером 1; самый лёгкий из элементов периодической таблицы. Его одноатомная форма — самое распространённое химическое вещество во Вселенной, составляющее примерно 75 % всей барионной массы.</span></span></span></a> фосфор практически не соединяется. Однако вода разлагает некоторые фосфиды по реакции, например:
                    <br><strong>Ca<sub>3</sub>P<sub>2</sub> + 6H<sub>2</sub>O → 2PH<sub>3</sub>↑ + 3Ca(OH)<sub>2</sub></strong>
                <br>может быть получен аналогичный аммиаку фосфористый водород (фосфин) — PH<sub>3</sub></p>  
                <h3>Взаимодействие с водой</h3>
                <p class="font-p">Взаимодействует с водяным паром при температуре выше 500 °С, протекает реакция диспропорционирования с образованием фосфина и фосфорной кислоты:
                    <br><strong>8P + 12H<sub>2</sub>O → 5PH<sub>3</sub>↑ + 3H<sub>3</sub>PO<sub>4</sub></strong>
                <br>Реакция взаимодействия красного фосфора и воды с образованием ортофосфорной кислоты и водорода. Реакция протекает при температуре 700—900 °C. Катализатором могут выступать: <a href="http://www.scienchemistry.org/web/HTML/Pt.html" class="mini-preview-anchor">платина<span class="mini-preview-wrapper" style="width: 320px; height: 408px; top: -412px;"><span class="mini-preview-loading" style="height: 396px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/metals/eight_row/Pt/Pt.jpg"><span class="p"><strong class="word">Платина</strong> —  химический элемент 10-й группы, 6-го периода периодической системы химических элементов, с атомным номером 78; блестящий благородный металл серебристо-белого цвета.</span></span></span></a>, <a href="http://www.scienchemistry.org/web/HTML/Cu.html" class="mini-preview-anchor">медь<span class="mini-preview-wrapper" style="width: 320px; height: 497px; top: -501px; left: -10px;"><span class="mini-preview-loading" style="height: 485px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/metals/nine_row/Cu/Cu.jpg"><span class="p"><strong class="word">Медь</strong> — химический элемент 11-й группы, четвёртого периода периодической системы, с атомным номером 29. Простое вещество медь — это пластичный переходный металл золотисто-розового цвета. C давних пор широко используется человеком.</span></span></span></a>, <a href="http://www.scienchemistry.org/web/HTML/Ti.html" class="mini-preview-anchor">титан<span class="mini-preview-wrapper" style="width: 320px; height: 445px; top: -449px;"><span class="mini-preview-loading" style="height: 433px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/metals/two_row/Ti/Ti.jpg"><span class="p"><strong class="word">Титан</strong> —  химический элемент с атомным номером 22. Принадлежит к 4-й группе периодической таблицы химических элементов, находится в четвёртом периоде таблицы.Простое вещество титан — лёгкий прочный металл серебристо-белого цвета.</span></span></span></a>, <a href="http://www.scienchemistry.org/web/HTML/Zr.html" class="mini-preview-anchor">цирконий<span class="mini-preview-wrapper" style="width: 320px; height: 464px; top: -468px;"><span class="mini-preview-loading" style="height: 452px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/metals/two_row/Zr/Zr1.png"><span class="p"><strong class="word">Цирконий</strong> — химический элемент с атомным номером 40. Принадлежит к 4-й группе периодической таблицы химических элементов, находится в пятом периоде таблицы. Простое вещество цирконий — блестящий металл серебристо-серого цвета. Обладает высокой пластичностью, устойчив к коррозии.</span></span></span></a>.               
                    <br><strong>2P + 8H<sub>2</sub>O → 2H<sub>3</sub>PO<sub>4</sub> + 5H<sub>2</sub>↑</strong></p>
                <h3>Взаимодействие со щелочами</h3>
                <p class="font-p">В холодных концентрированных растворах щелочей также медленно протекает реакция диспропорционирования с образованием фосфина:
                    <br><strong>4P + 3KOH + 3H<sub>2</sub>O → PH<sub>3</sub>↑ + 3KH<sub>2</sub>PO<sub>2</sub></strong></p>
                <h3>Восстановительные свойства</h3>
                <p class="font-p">Сильные окислители превращают фосфор в фосфорную кислоту:
                    <br><strong>3P + 5HNO<sub>3</sub> + 2H<sub>2</sub>O → 3H<sub>3</sub>PO<sub>4</sub> + 5NO↑</strong>
                    <br><strong>2P + 5H<sub>2</sub>SO<sub>4</sub> → 2H<sub>3</sub>PO<sub>4</sub> + 5SO<sub>2</sub>↑ + 2H<sub>2</sub>O</strong>
                <br>Реакция окисления фосфора происходит при поджигании спичек, в качестве окислителя выступает бертолетова соль:
                    <br><strong>6P + 5KClO<sub>3</sub> → + 5KCl + 3P<sub>2</sub>O<sub>5</sub></strong>
                    <br><strong>2P + KClO<sub>3</sub> → KCl + P<sub>2</sub>O<sub>3</sub></strong>
                <h2  class="elements" >Историческая справка</h2>
                <p class="font-p">Фосфор открыт гамбургским алхимиком <a href="http://www.scienchemistry.org/web/HistoricalFigures/Hennig Brand.html" class="mini-preview-anchor">Хеннигом Брандом<span class="mini-preview-wrapper" style="width: 320px; height: 343px; top: -347px;"><span class="mini-preview-loading" style="height: 331px;"><img class="mini-preview-img" src="http://chemistry.com/HistoricalFigures/Hennig Brand/img2.jpg"><span class="p"><strong class="word">Хенниг Бранд</strong> — немецкий алхимик. Считается, что в 1669 году он открыл фосфор.</span></span></span></a> в 1669 году. Подобно другим алхимикам, Бранд пытался отыскать философский камень, а получил светящееся вещество. Бранд сфокусировался на опытах с человеческой мочой, так как полагал, что она, обладая золотистым цветом, может содержать золото или нечто нужное для его добычи. Первоначально его способ заключался в том, что сначала моча отстаивалась в течение нескольких дней, пока не исчезнет неприятный запах, а затем кипятилась до клейкого состояния. Нагревая эту пасту до высоких температур и доводя до появления пузырьков, он надеялся, что, сконденсировавшись, они будут содержать золото. После нескольких часов интенсивных кипячений получались крупицы белого воскоподобного вещества, которое очень ярко горело и к тому же мерцало в темноте. Бранд назвал это вещество phosphorus mirabilis (лат. «чудотворный носитель света»). Открытие фосфора Брандом стало первым открытием нового элемента со времён античности.</p>
                <div class="thumb-tright">
                    <div class="thumbinner" style="width:302px;">
                        <img alt="Na"  src="http://chemistry.com/Elements/Image/Nonmetals/P/P1.jpg" style="width:300px;"> 
                        <div class="thumbcaption">
                            <p class="font-p" style="margin:0;font-size:16px;">Картина Джозефа Райта «Алхимик, открывающий фосфор» (1771 год), предположительно описывающая открытие фосфора Хеннигом Брандом.</p>
                        </div>
                    </div>
                </div> 
                <p class="font-p">Несколько позже фосфор был получен другим немецким химиком — Иоганном Кункелем.</p>
                <p class="font-p">Независимо от Бранда и Кункеля фосфор был получен <a href="http://www.scienchemistry.org/web/HistoricalFigures/Robert Boyle.html" class="mini-preview-anchor">Р. Бойлем<span class="mini-preview-wrapper" style="width: 320px; height: 362px; top: -366px; left: -10px;"><span class="mini-preview-loading" style="height: 350px;"><img class="mini-preview-img" src="http://chemistry.com/HistoricalFigures/Robert Boyle/img2.jpg"><span class="p"><strong class="word">Роберт Бойль</strong> — англо-ирландский натурфилософ, физик, химик и богослов. Седьмой сын Ричарда Бойля, 1-го графа Коркского, вельможи времён Елизаветы Английской.</span></span></span></a>, описавшим его в статье «Способ приготовления фосфора из человеческой мочи», датированной 14 октября 1680 года и опубликованной в 1693 году.</p>
                <p class="font-p">Более усовершенствованный способ получения фосфора был опубликован в 1743 году Андреасом Маргграфом.</p>
                <p class="font-p">Существуют данные, что фосфор умели получать ещё арабские алхимики в XII в.</p>
                <p class="font-p">То, что фосфор — простое вещество, доказал <a href="http://www.scienchemistry.org/web/HistoricalFigures/Antoine Laurent.html" class="mini-preview-anchor">Лавуазье<span class="mini-preview-wrapper" style="width: 320px; height: 448px; top: -452px; left: -10px;"><span class="mini-preview-loading" style="height: 436px;"><img class="mini-preview-img" src="http://chemistry.com/HistoricalFigures/Antoine Laurent/img2.jpg"><span class="p"><strong class="word">Антуан Лавуазье</strong> — французский естествоиспытатель, основатель современной химии.</span></span></span></a>.</p>
                <p class="font-p">Аморфную аллотропную модификацию фосфора — красный фосфор Р<sub>n</sub> — выделил, нагревая белый фосфор без доступа воздуха, А. Шрёттер в середине XIX в.</p>
                <h3>Происхождение названия</h3>
                <p class="font-p">В 1669 году <a href="http://www.scienchemistry.org/web/HistoricalFigures/Hennig Brand.html" class="mini-preview-anchor">Хенниг Бранд<span class="mini-preview-wrapper" style="width: 320px; height: 343px; top: -347px;"><span class="mini-preview-loading" style="height: 331px;"><img class="mini-preview-img" src="http://chemistry.com/HistoricalFigures/Hennig Brand/img2.jpg"><span class="p"><strong class="word">Хенниг Бранд</strong> — немецкий алхимик. Считается, что в 1669 году он открыл фосфор.</span></span></span></a> при нагревании смеси белого песка и выпаренной мочи получил светящееся в темноте вещество, названное сначала «холодным огнём». Вторичное название «фосфор» происходит от греческих слов «φώς» — свет и «φέρω» — несу. В древнегреческой мифологии имя Фосфор (или Эосфор, др.-греч. Φωσφόρος) носил страж Утренней звезды.</p>
            </div>
        </div>
    </div>
</body>
</html> 