<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <title>Химия</title>
    <link rel="stylesheet" type="text/css" href="http://scienchemistry.org/web/CSS/style.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@700&family=Rubik+Mono+One&family=Bad+Script&family=Jura:wght@300&family=Balsamiq+Sans:ital@1&display=swap" rel="stylesheet">
    <link rel="icon" type="image/png" href="http://chemistry.com/Picture/icon.png">
</head>
<body>        
    <div class="wrapper">
        <!--#include virtual="/web/Sitedesign/Menu.html"-->
        <div class="container2">
            <!--#include virtual="/web/Sitedesign/Tablestructure.html"-->
        </div>    
        <div class="container">
            <div class="information"  id="Ar">
                <h1 class="elements">Аргон</h1>
                <hr>
                <div class="table">
                    <table class='infobox'>
                        <tbody>
                            <tr>
                                <th class="plainlist" colspan="2">Химические элементы</th>
                            </tr>
                            <tr>
                                <th class="definition" colspan="2" style="background: #1b1e20;color: #759ffe;">Ar</th>
                            </tr>
                            <tr>
                                <th colspan="2">
                                    <img class="E-img" src="http://chemistry.com/Elements/Image/In.gases/Ar/Ar.gif">
                                </th>
                            </tr>
                            <tr>
                                <th class="plainlist">Предмет изучения</th>
                                <td class="definition" style="color: #759ffe;">Химия</td>
                            </tr>
                            <tr>
                                <th class="plainlist">Период  зарождения</th>
                                <td class="definition" style="color: #759ffe;" >7 августа 1894 г.</td>
                            </tr>
                            <tr>
                                <th class="plainlist">Используется в</th>
                                <td class="definition" style="color: #759ffe;">лампах накаливания, аргоновых лазерах</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <p class="font-p"><strong class="preface">Аргон</strong> — это химический элемент 18-й группы периодической таблицы <a href="http://www.scienchemistry.org/web/HistoricalFigures/Mendeleev.html" class="mini-preview-anchor">Д.И.Менделеева<span class="mini-preview-wrapper" style="width: 320px; height: 490px; top: -498px;"><span class="mini-preview-loading" style="height: 478px;"><img class="mini-preview-img" src="http://chemistry.com/HistoricalFigures/Mendeleev/img.jpg"><span class="p"><strong class="word">Д.И.Менделеев</strong> — русский учёный-энциклопедист: химик, физикохимик, физик и так далее. Среди самых известных открытий — периодический закон химических элементов, один из фундаментальных законов мироздания, неотъемлемый для всего естествознания.</span></span></span></a>, третьего периода, с атомным номером 18. Обозначается символом Ar (лат. Argon). Третий по распространённости химический элемент в воздухе земной атмосферы (после <a href="http://www.scienchemistry.org/web/HTML/N.html" class="mini-preview-anchor">азота<span class="mini-preview-wrapper" style="width: 320px; height: 435px; top: -439px;"><span class="mini-preview-loading" style="height: 423px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/Nonmetals/N/N.jpg"><span class="p"><strong class="word">Азот</strong> — химический элемент 15-й группы, второго периода периодической системы, с атомным номером 7.Как простое вещество представляет собой двухатомный газ без цвета, вкуса и запаха.Один из самых распространённых элементов на Земле.</span></span></span></a> и <a href="http://www.scienchemistry.org/web/HTML/O.html" class="mini-preview-anchor">кислорода<span class="mini-preview-wrapper" style="width: 320px; height: 458px; top: -462px; left: -10px;"><span class="mini-preview-loading" style="height: 446px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/Nonmetals/O/O.jpg"><span class="p"><strong class="word">Кислород</strong> — химический элемент 16-й группы, второго периода периодической системы, с атомным номером 8.Кислород — химически активный неметалл, является самым лёгким элементом из группы халькогенов.</span></span></span></a>) — 0,93 % по объёму. Простое вещество аргон — инертный одноатомный газ без цвета, вкуса и запаха.</p>
                <h2  class="elements">Физические свойства</h2>
                <p class="font-p"><strong class="word">Аргон</strong> — одноатомный газ с температурой кипения (при нормальном давлении) −185,9 °C (немного ниже, чем у <a href="http://www.scienchemistry.org/web/HTML/O.html" class="mini-preview-anchor">кислорода<span class="mini-preview-wrapper" style="width: 320px; height: 458px; top: -462px; left: -10px;"><span class="mini-preview-loading" style="height: 446px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/Nonmetals/O/O.jpg"><span class="p"><strong class="word">Кислород</strong> — химический элемент 16-й группы, второго периода периодической системы, с атомным номером 8.Кислород — химически активный неметалл, является самым лёгким элементом из группы халькогенов.</span></span></span></a>, но немного выше, чем у <a href="http://www.scienchemistry.org/web/HTML/N.html" class="mini-preview-anchor">азота<span class="mini-preview-wrapper" style="width: 320px; height: 435px; top: -439px;"><span class="mini-preview-loading" style="height: 423px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/Nonmetals/N/N.jpg"><span class="p"><strong class="word">Азот</strong> — химический элемент 15-й группы, второго периода периодической системы, с атомным номером 7.Как простое вещество представляет собой двухатомный газ без цвета, вкуса и запаха.Один из самых распространённых элементов на Земле.</span></span></span></a>). В 100 мл воды при 20 °C растворяется 3,3 мл аргона, в некоторых органических растворителях аргон растворяется значительно лучше, чем в воде. Плотность при нормальных условиях составляет 1,7839 кг/м³.</p>
                <h2>Химические свойства</h2>
                <div class="thumb-tright">
                    <div class="thumbinner" style="width:222px;">
                        <img alt="H1"  src="http://chemistry.com/Elements/Image/In.gases/Ar/Ar1.png" style="width:220px;"> 
                        <div class="thumbcaption">
                            <p class="font-p" style="margin:0;font-size:16px;">Спектр аргона</p>
                        </div>
                    </div>
                </div>  
                <div class="thumb-tright">
                    <div class="thumbinner" style="width:222px;">
                        <img alt="H3"  src="http://chemistry.com/Elements/Image/In.gases/Ar/Ar1.jpg" style="width:220px;"> 
                        <div class="thumbcaption">
                            <p class="font-p" style="margin:0;font-size:16px;">Заполненная аргоном и парами ртути газоразрядная трубка</p>
                        </div>
                    </div>
                </div>
                <p class="font-p">Пока известны только 2 химических соединения аргона — гидрофторид аргона и CU(Ar)O, которые существуют при очень низких температурах. Кроме того, аргон образует эксимерные молекулы, то есть молекулы, у которых устойчивы возбуждённые электронные состояния и неустойчиво основное состояние. Есть основания считать, что исключительно нестойкое соединение Hg—Ar, образующееся в электрическом разряде, — это подлинно химическое (валентное) соединение. Не исключено, что будут получены другие валентные соединения аргона с <a href="http://www.scienchemistry.org/web/HTML/F.html" class="mini-preview-anchor">фтором<span class="mini-preview-wrapper" style="width: 320px; height: 522px; top: -526px; left: -10px;"><span class="mini-preview-loading" style="height: 510px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/Nonmetals/F/F.jpg"><span class="p"><strong class="word">Фтор</strong> — химический элемент 17-й группы, второго периода периодической системы, с атомным номером 9,двухатомный газ бледно-жёлтого цвета с резким запахом. Самый химически активный неметалл и сильнейший окислитель.</span></span></span></a> и <a href="http://www.scienchemistry.org/web/HTML/O.html" class="mini-preview-anchor">кислородом<span class="mini-preview-wrapper" style="width: 320px; height: 458px; top: -462px; left: -10px;"><span class="mini-preview-loading" style="height: 446px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/Nonmetals/O/O.jpg"><span class="p"><strong class="word">Кислород</strong> — химический элемент 16-й группы, второго периода периодической системы, с атомным номером 8.Кислород — химически активный неметалл, является самым лёгким элементом из группы халькогенов.</span></span></span></a>, которые тоже должны быть крайне неустойчивыми. Например, при электрическом возбуждении смеси аргона и <a href="http://www.scienchemistry.org/web/HTML/Cl.html" class="mini-preview-anchor">хлором<span class="mini-preview-wrapper" style="width: 320px; height: 557px; top: -561px; left: -10px;"><span class="mini-preview-loading" style="height: 545px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/Nonmetals/Cl/Cl.jpg"><span class="p"><strong class="word">Хлор</strong> — химический элемент 17-й группы, третьего периода переодической системы, с атомным номером 17. Простое вещество хлор при нормальных условиях — ядовитый газ желтовато-зелёного цвета, тяжелее воздуха, с резким запахом и сладковатым, «металлическим» вкусом.</span></span></span></a> возможна газофазная реакция с образованием ArCl. Также со многими веществами, между молекулами которых действуют водородные связи (водой, фенолом, гидрохиноном и другими), образует соединения включения (клатраты), где атом аргона, как своего рода «гость», находится в полости, образованной в кристаллической решётке молекулами вещества-хозяина, например, Ar·6H<sub>2</sub>O.</p>
                <p class="font-p">Соединение CU(Ar)O получено из соединения <a href="http://www.scienchemistry.org/web/HTML/U.html" class="mini-preview-anchor">урана<span class="mini-preview-wrapper" style="width: 320px; height: 459px; top: -463px; left: -10px;"><span class="mini-preview-loading" style="height: 447px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/57-71and89-103/Aktin/U/U.jpg"><span class="p"><strong class="word">Уран</strong> — химический элемент, принадлежащий к актиноидам, с атомным номером 92. Уран — слабо радиоактивный элемент, он не имеет стабильных изотопов. Самыми известными изотопами урана являются уран-238 и уран-235.</span></span></span></a> с <a href="http://www.scienchemistry.org/web/HTML/C.html" class="mini-preview-anchor">углеродом<span class="mini-preview-wrapper" style="width: 320px; height: 502px; top: -506px;"><span class="mini-preview-loading" style="height: 490px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/Nonmetals/C/C.jpg"><span class="p"><strong class="word">Углерод</strong> —  химический элемент, обозначающийся буквой C и имеющий атомный номер 6. Он располагается в 14-й группе периодической системы. Углерод был известен ещё в античном мире.</span></span></span></a> и <a href="http://www.scienchemistry.org/web/HTML/O.html" class="mini-preview-anchor">кислородом<span class="mini-preview-wrapper" style="width: 320px; height: 458px; top: -462px; left: -10px;"><span class="mini-preview-loading" style="height: 446px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/Nonmetals/O/O.jpg"><span class="p"><strong class="word">Кислород</strong> — химический элемент 16-й группы, второго периода периодической системы, с атомным номером 8.Кислород — химически активный неметалл, является самым лёгким элементом из группы халькогенов.</span></span></span></a> CUO. Вероятно существование соединений со связями Ar—Si и Ar—C: FArSiF<sub>3</sub> и FArCCH.</p>         
                <h2  class="elements">Изотопы</h2>
                <p class="font-p">Аргон представлен в земной атмосфере тремя стабильными изотопами: <sup>36</sup>Ar (0,337 %), <sup>38</sup>Ar (0,063 %), <sup>40</sup>Ar (99,600 %). Почти вся масса тяжёлого изотопа <sup>40</sup>Ar возникла на Земле в результате распада радиоактивного изотопа <a href="http://www.scienchemistry.org/web/HTML/K.html" class="mini-preview-anchor">калия<span class="mini-preview-wrapper" style="width: 320px; height: 503px; top: -507px;"><span class="mini-preview-loading" style="height: 491px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/metals/first_group/K/K.jpg"><span class="p"><strong class="word">Калий</strong> — химический элемент первой группы, четвёртого периода периодической системы, с атомным номером 19, мягкий щелочной металл серебристо-белого цвета.В природе калий встречается только в соединениях с другими элементами, например, в морской воде, а также во многих минералах.</span></span></span></a> <sup>40</sup>K (содержание этого изотопа в изверженных породах в среднем составляет 3,1 г/т). Распад радиоактивного калия идёт по двум направлениям одновременно:
                    <br><strong><sup>40</sup>₁₉K → <sup>40</sup>₂₀Ca + e⁻ + ṽ<sub>e</sub></strong>
                    <br><strong><sup>40</sup>₁₉K + e⁻ → <sup>40</sup>₁₈Ar + ṽ<sub>e</sub> + γ</strong>
                <br>Первый процесс (обычный β-распад) протекает в 88 % случаев и ведёт к возникновению стабильного изотопа <a href="http://www.scienchemistry.org/web/HTML/Ca.html" class="mini-preview-anchor">кальция<span class="mini-preview-wrapper" style="width: 320px; height: 434px; top: -438px; left: -10px;"><span class="mini-preview-loading" style="height: 422px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/metals/second_group/Ca/Ca.jpg"><span class="p"><strong class="word">Кальций</strong> — элемент второй группы, четвёртого периода, с атомным номером 20. Простое вещество кальций — мягкий, химически активный щёлочноземельный металл серебристо-белого цвета. Впервые получен в чистом виде Г. Дэви в 1808 году.</span></span></span></a>. Во втором процессе, где участвуют 12 % атомов, происходит электронный захват, в результате чего образуется тяжёлый изотоп аргона. Одна тонна калия, содержащегося в горных породах или водах, в течение года генерирует приблизительно 3100 атомов аргона. Таким образом, в минералах, содержащих калий, постепенно накапливается <sup>40</sup>Ar, что позволяет измерять возраст горных пород; калий-аргоновый метод является одним из основных методов ядерной геохронологии.</p>
                <p class="font-p">Вероятные источники происхождения изотопов <sup>36</sup>Ar и <sup>38</sup>Ar — неустойчивые продукты спонтанного деления тяжёлых ядер, а также реакции захвата нейтронов и альфа-частиц ядрами лёгких элементов, содержащихся в урано-ториевых минералах.</p>
                <p class="font-p">Подавляющая часть космического аргона состоит из изотопов <sup>36</sup>Ar и <sup>38</sup>Ar. Это вызвано тем обстоятельством, что калий распространён в космосе примерно в 50 000 раз меньше, чем аргон (на Земле калий преобладает над аргоном в 660 раз). Примечателен произведенный геохимиками подсчёт: вычтя из аргона земной атмосферы радиогенный <sup>40</sup>Ar, они получили изотопный состав, очень близкий к составу космического аргона.</p>
                <h2  class="elements" >Историческая справка</h2>
                <p class="font-p">История открытия аргона начинается в 1785 году, когда английский физик и химик <a href="http://www.scienchemistry.org/web/HistoricalFigures/Henry Cavendish.html" class="mini-preview-anchor">Генри Кавендиш<span class="mini-preview-wrapper" style="width: 320px; height: 456px; top: -460px; left: -10px;"><span class="mini-preview-loading" style="height: 444px;"><img class="mini-preview-img" src="http://chemistry.com/HistoricalFigures/Henry Cavendish/img.jpg"><span class="p"><strong class="word">Генри Кавендиш</strong> — британский физик и химик.Член Лондонского королевского общества (1760), иностранный член Парижской академии наук (1803).</span></span></span></a>, изучая состав воздуха, решил установить, весь ли <a href="http://www.scienchemistry.org/web/HTML/N.html" class="mini-preview-anchor">азот<span class="mini-preview-wrapper" style="width: 320px; height: 435px; top: -439px;"><span class="mini-preview-loading" style="height: 423px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/Nonmetals/N/N.jpg"><span class="p"><strong class="word">Азот</strong> — химический элемент 15-й группы, второго периода периодической системы, с атомным номером 7.Как простое вещество представляет собой двухатомный газ без цвета, вкуса и запаха.Один из самых распространённых элементов на Земле.</span></span></span></a> воздуха окисляется. В течение многих недель он подвергал воздействию электрического разряда смесь воздуха с <a href="http://www.scienchemistry.org/web/HTML/O.html" class="mini-preview-anchor">кислородом<span class="mini-preview-wrapper" style="width: 320px; height: 458px; top: -462px; left: -10px;"><span class="mini-preview-loading" style="height: 446px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/Nonmetals/O/O.jpg"><span class="p"><strong class="word">Кислород</strong> — химический элемент 16-й группы, второго периода периодической системы, с атомным номером 8.Кислород — химически активный неметалл, является самым лёгким элементом из группы халькогенов.</span></span></span></a> в U-образных трубках, в результате чего в них образовывались всё новые порции бурых оксидов азота, которые исследователь периодически растворял в щёлочи. Через некоторое время образование окислов прекратилось, но после связывания оставшегося кислорода остался пузырёк газа, объём которого не уменьшался при длительном воздействии электрических разрядов в присутствии кислорода. Кавендиш оценил объём оставшегося газового пузыря в 1/120 от первоначального объёма воздуха. Разгадать загадку пузыря Кавендиш не смог, поэтому прекратил своё исследование и даже не опубликовал его результатов. Только спустя много лет английский физик Джеймс Максвелл собрал и опубликовал неизданные рукописи и лабораторные записки Кавендиша.</p>
                <p class="font-p">Дальнейшая история открытия аргона связана с именем Рэлея, который несколько лет посвятил исследованиям плотности газов, особенно азота. Оказалось, что литр азота, полученного из воздуха, весил больше литра «химического» азота (полученного путём разложения какого-либо азотистого соединения, например, закиси азота, окиси азота, аммиака, мочевины или селитры) на 1,6 мг (масса первого была равна 1,2521 г, а второго — 1,2505 г). Эта разница была не так уж мала, чтобы можно было её отнести на счёт ошибки опыта. К тому же она постоянно повторялась независимо от источника получения химического азота.</p>
                <p class="font-p">Не придя к разгадке, осенью 1892 года Рэлей в журнале «Nature» опубликовал письмо к учёным с просьбой дать объяснение тому факту, что в зависимости от способа выделения азота он получал разные величины плотности. Письмо прочли многие учёные, однако никто не был в состоянии ответить на поставленный в нём вопрос.</p>    
                <p class="font-p">У известного уже в то время английского химика <a href="http://www.scienchemistry.org/web/HistoricalFigures/William Ramsay.html" class="mini-preview-anchor">Уильяма Рамзая<span class="mini-preview-wrapper" style="width: 320px; height: 482px; top: -486px; left: -10px;"><span class="mini-preview-loading" style="height: 470px;"><img class="mini-preview-img" src="http://chemistry.com/HistoricalFigures/William Ramsay/img2.jpg"><span class="p"><strong class="word">Уильям Рамзай</strong> — шотландский британский химик и физик, лауреат Нобелевской премии по химии 1904 года. Открыл неон, аргон, криптон, ксенон и показал, что они с гелием и радоном формируют отдельную группу новых элементов — инертные газы.</span></span></span></a> также не было готового ответа, но он предложил Рэлею своё сотрудничество. Интуиция побудила Рамзая предположить, что азот воздуха содержит примеси неизвестного и более тяжёлого газа, а Дьюар обратил внимание Рэлея на описание старинных опытов Кавендиша (которые уже были к этому времени опубликованы).</p>
                <p class="font-p">Пытаясь выделить из воздуха скрытую составную часть, каждый из учёных пошёл своим путём. Рэлей повторил опыт Кавендиша в увеличенном масштабе и на более высоком техническом уровне. Трансформатор под напряжением 6000 вольт посылал в 50-литровый колокол, заполненный азотом, сноп электрических искр. Специальная турбина создавала в колоколе фонтан брызг раствора щёлочи, поглощающих окислы азота и примесь углекислоты. Оставшийся газ Рэлей высушил и пропустил через фарфоровую трубку с нагретыми <a href="http://www.scienchemistry.org/web/HTML/Cu.html" class="mini-preview-anchor">медными<span class="mini-preview-wrapper" style="width: 320px; height: 497px; top: -501px; left: -10px;"><span class="mini-preview-loading" style="height: 485px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/metals/nine_row/Cu/Cu.jpg"><span class="p"><strong class="word">Медь</strong> — химический элемент 11-й группы, четвёртого периода периодической системы, с атомным номером 29. Простое вещество медь — это пластичный переходный металл золотисто-розового цвета. C давних пор широко используется человеком.</span></span></span></a> опилками, задерживающими остатки кислорода. Опыт длился несколько дней.</p>
                <p class="font-p">Рамзай воспользовался открытой им способностью нагретого металлического магния поглощать азот, образуя твёрдый нитрид <a href="http://www.scienchemistry.org/web/HTML/Mg.html" class="mini-preview-anchor">магния<span class="mini-preview-wrapper" style="width: 320px; height: 395px; top: -399px; left: -10px;"><span class="mini-preview-loading" style="height: 383px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/metals/second_group/Mg/Mg.jpg"><span class="p"><strong class="word">Магний</strong> — элемент 2 группы, третьего периода периодической системы химических элементов Д. И. Менделеева, с атомным номером 12. Простое вещество магний — лёгкий, ковкий металл серебристо-белого цвета.</span></span></span></a>. Многократно пропускал он несколько литров азота через собранный им прибор. Через 10 дней объём газа перестал уменьшаться, следовательно, весь азот оказался связанным. Одновременно путём соединения с медью был удалён кислород, присутствовавший в качестве примеси к азоту. Этим способом Рамзаю в первом же опыте удалось выделить около 100 мл нового газа.</p>
                <p class="font-p">Итак, был открыт новый газ. Стало известно, что он тяжелее азота почти в полтора раза и составляет 1/80 часть объёма воздуха. Рамзай при помощи акустических измерений нашёл, что молекула нового газа состоит из одного атома — до этого подобные газы в устойчивом состоянии не встречались. Отсюда следовал очень важный вывод — раз молекула одноатомна, то, очевидно, новый газ представляет собой не сложное химическое соединение, а простое вещество.</p>     
                <p class="font-p">Много времени затратили Рамзай и Рэлей на изучение его реакционной способности по отношению ко многим химически активным веществам. Но, как и следовало ожидать, пришли к выводу: их газ совершенно недеятелен. Это было ошеломляюще — до той поры не было известно ни одного настолько инертного вещества.</p>
                <p class="font-p">Большую роль в изучении нового газа сыграл спектральный анализ. Спектр выделенного из воздуха газа с его характерными оранжевыми, синими и зелёными линиями резко отличался от спектров уже известных газов. Уильям Крукс, один из виднейших спектроскопистов того времени, насчитал в его спектре почти 200 линий. Уровень развития спектрального анализа на то время не дал возможности определить, одному или нескольким элементам принадлежал наблюдаемый спектр. Несколько лет спустя выяснилось, что Рамзай и Рэлей держали в своих руках не одного незнакомца, а нескольких — целую плеяду инертных газов.</p>
                <p class="font-p">7 августа 1894 года в Оксфорде, на собрании Британской ассоциации физиков, химиков и естествоиспытателей, было сделано сообщение об открытии нового элемента, который был назван аргоном. В своём докладе Рэлей утверждал, что в каждом кубическом метре воздуха присутствует около 15 г открытого газа (1,288 % по массе). Слишком невероятен был тот факт, что несколько поколений учёных не заметили составной части воздуха, да ещё и в количестве целого процента! В считанные дни десятки естествоиспытателей из разных стран проверили опыты Рамзая и Рэлея. Сомнений не оставалось: воздух содержит аргон.</p>
                <p class="font-p">Через 10 лет, в 1904 году, Рэлей за исследования плотностей наиболее распространённых газов и открытие аргона получает Нобелевскую премию по физике, а Рамзай за открытие в атмосфере различных инертных газов — Нобелевскую премию по химии.</p>
                <h3>Происхождение названия</h3>
                <p class="font-p">По предложению доктора Медана (председателя заседания, на котором был сделан доклад об открытии) Рэлей и Рамзай дали новому газу имя «аргон» (от др.-греч. ἀργός — ленивый, медленный, неактивный). Это название подчёркивало важнейшее свойство элемента — его химическую неактивность.</p>
            </div>
        </div>
    </div>
</body>
</html>         