<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <title>Химия</title>
    <link rel="stylesheet" type="text/css" href="http://scienchemistry.org/web/CSS/style.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@700&family=Rubik+Mono+One&family=Bad+Script&family=Jura:wght@300&family=Balsamiq+Sans:ital@1&display=swap" rel="stylesheet">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script> 
</head>
<body>        
    <div class="wrapper">
        <!--#include virtual="/web/Sitedesign/Menu.html"-->
        <div class="container2">
            <!--#include virtual="/web/Sitedesign/Tablestructure.html"-->
        </div>
        <div class="container">
            <div class="information"  id="Cl">
                <h1 class="elements">Хлор</h1>
                <hr>
                <div class='t'>
                    <table class='infobox'>
                        <tbody>
                            <tr>
                                <th class='plainlist' colspan="2">Химические элементы</th>
                            </tr>
                            <tr>
                                <th class='definition' colspan="2" style="background: #1b1e20;color:#53ee61;">Cl</th>
                            </tr>
                            <tr>
                                <th colspan="2">
                                    <img class="E-img" src="http://chemistry.com/Elements/Image/Nonmetals/Cl/Cl.gif">
                                </th>
                            </tr>
                            <tr>
                                <th class='plainlist'>Предмет изучения</th>
                                <td class='definition' style="color:#53ee61;">Химия</td>
                            </tr>
                            <tr>
                                <th class='plainlist'>Период  зарождения</th>
                                <td class='definition' style="color:#53ee61;">1772-1774 г.</td>
                            </tr>
                            <tr>
                                <th class='plainlist'>Используется в</th>
                                <td class='definition' style="color:#53ee61;">производстве, процессах отбеливания, металлургии</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <p class="font-p"><strong class="preface">Хлор</strong> - это химический элемент с атомным номером 17. Принадлежит к 17-й группе периодической таблицы <a href="http://www.scienchemistry.org/web/HistoricalFigures/Mendeleev.html" class="mini-preview-anchor">Д.И.Менделеева<span class="mini-preview-wrapper" style="width: 320px; height: 490px; top: -498px;"><span class="mini-preview-loading" style="height: 478px;"><img class="mini-preview-img" src="http://chemistry.com/HistoricalFigures/Mendeleev/img.jpg"><span class="p"><strong class="word">Д.И.Менделеев</strong> — русский учёный-энциклопедист: химик, физикохимик, физик и так далее. Среди самых известных открытий — периодический закон химических элементов, один из фундаментальных законов мироздания, неотъемлемый для всего естествознания.</span></span></span></a> (по устаревшей короткой форме периодической системы принадлежит к главной подгруппе VII группы, или к группе VIIA), находится в третьем периоде таблицы. Атомная масса элемента 35,446...35,457. Обозначается символом Cl (от лат. Chlorum). Химически активный неметалл. Входит в группу галогенов.</p>
                <p class="font-p">Простое вещество хлор при нормальных условиях — ядовитый газ желтовато-зелёного цвета, тяжелее воздуха, с резким запахом и сладковатым, «металлическим» вкусом. Молекула хлора двухатомная (формула Cl<sub>2</sub> ).</p>
                <h2  class="elements" >Физические свойства</h2>
                <p class="font-p">При нормальных условиях хлор — жёлто-зелёный газ с удушающим запахом.</p>
                <p class="font-p">Газообразный хлор относительно легко сжижается. Начиная с давления в 0,8 МПа (8 атмосфер), хлор будет жидким уже при комнатной температуре. При охлаждении до температуры в −34 °C хлор тоже становится жидким при нормальном атмосферном давлении. Жидкий хлор — жёлто-зелёная жидкость, обладающая очень высоким коррозионным действием (за счёт высокой концентрации молекул). Повышая давление, можно добиться существования жидкого хлора вплоть до температуры в +144 °C (критической температуры) при критическом давлении в 7,6 МПа.</p>
                <p class="font-p">При температуре ниже −101 °C жидкий хлор кристаллизуется в орторомбическую решётку с пространственной группой Cmca и параметрами a = 6,29 Å, b = 4,50 Å, c = 8,21 Å. Ниже 100 К орторомбическая модификация кристаллического хлора переходит в тетрагональную, имеющую пространственную группу P4<sub>2</sub> /ncm и параметры решётки a = 8,56 Å и c = 6,12 Å.</p>
                <p class="font-p">Степень диссоциации молекулы хлора Cl<sub>2</sub> → 2Cl при 1000 К равна 2,07⋅10<sup>−4</sup>%, а при 2500 К — 0,909 %.</p>
                <p class="font-p">Порог восприятия запаха в воздухе равен 2—3 мг/м³.</p>
                <p class="font-p">По электропроводности жидкий хлор занимает место среди самых сильных изоляторов: он проводит ток почти в миллиард раз хуже, чем дистиллированная вода, и в 10<sup>22</sup> раз хуже <a href="http://www.scienchemistry.org/web/HTML/Ag.html" class="mini-preview-anchor">серебра<span class="mini-preview-wrapper" style="width: 320px; height: 417px; top: -421px; left: -10px;"><span class="mini-preview-loading" style="height: 405px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/metals/nine_row/Ag/Ag.jpg"><span class="p"><strong class="word">Серебро</strong> — элемент 11 группы, пятого периода периодической системы химических элементов Д. И. Менделеева, с атомным номером 47. Простое вещество серебро — ковкий, пластичный благородный металл серо-белого цвета.</span></span></span></a>. Скорость звука в газообразном хлоре примерно в полтора раза меньше, чем в воздухе.</p>
                <h2  class="elements" >Химические свойства</h2> 
                <div class="thumb-tright">
                    <div class="thumbinner" style="width:222px;">
                        <img alt="Cl1"  src="http://chemistry.com/Elements/Image/Nonmetals/Cl/Cl1.jpg" style="width:220px;"> 
                        <div class="thumbcaption">
                            <p class="font-p" style="margin:0;font-size:16px;">Газообразный хлор в ампуле</p>
                        </div>
                    </div>
                </div>
                <p  class="font-p">На валентном уровне атома хлора содержится 1 неспаренный электрон: 1s<sup>2</sup> 2s<sup>2</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>5</sup>, поэтому валентность, равная 1 для атома хлора, очень стабильна. За счёт присутствия в атоме хлора незанятой орбитали d-подуровня атом хлора может проявлять и другие степени окисления.</p>
                <p class="font-p">Также известны соединения хлора, в которых атом хлора формально проявляет валентности IV и VI, например, ClO<sub>2</sub> и Cl<sub>2</sub>O<sub>6</sub> . Однако оксид хлора(IV) является стабильным радикалом, то есть имеет неспаренный электрон, а оксид хлора(VI) содержит два атома хлора, имеющих степени окисления +5 и +7.</p>
                <p class="font-p">Хлор непосредственно реагирует почти со всеми металлами (с некоторыми только в присутствии влаги или при нагревании):
                    <br><strong>2Na + Cl<sub>2</sub> → 2NaCl</strong>
                    <br><strong>2Sb + 3Cl<sub>2</sub> → 2SbCl<sub>3</sub></strong>
                    <br><strong>2Fe + 3Cl<sub>2</sub> → 2FeCl<sub>3</sub></strong>
                <br>C неметаллами (кроме <a href="http://www.scienchemistry.org/web/HTML/C.html" class="mini-preview-anchor">углерода<span class="mini-preview-wrapper" style="width: 320px; height: 502px; top: -506px;"><span class="mini-preview-loading" style="height: 490px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/Nonmetals/C/C.jpg"><span class="p"><strong class="word">Углерод</strong> —  химический элемент, обозначающийся буквой C и имеющий атомный номер 6. Он располагается в 14-й группе периодической системы. Углерод был известен ещё в античном мире.</span></span></span></a>, <a href="http://www.scienchemistry.org/web/HTML/N.html" class="mini-preview-anchor">азота<span class="mini-preview-wrapper" style="width: 320px; height: 435px; top: -439px;"><span class="mini-preview-loading" style="height: 423px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/Nonmetals/N/N.jpg"><span class="p"><strong class="word">Азот</strong> — химический элемент 15-й группы, второго периода периодической системы, с атомным номером 7.Как простое вещество представляет собой двухатомный газ без цвета, вкуса и запаха.Один из самых распространённых элементов на Земле.</span></span></span></a>, <a href="http://www.scienchemistry.org/web/HTML/F.html" class="mini-preview-anchor">фтора<span class="mini-preview-wrapper" style="width: 320px; height: 522px; top: -526px;"><span class="mini-preview-loading" style="height: 510px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/Nonmetals/F/F.jpg"><span class="p"><strong class="word">Фтор</strong> — химический элемент 17-й группы, второго периода периодической системы, с атомным номером 9;двухатомный газ бледно-жёлтого цвета с резким запахом. Самый химически активный неметалл и сильнейший окислитель.</span></span></span></a>, <a href="http://www.scienchemistry.org/web/HTML/O.html" class="mini-preview-anchor">кислорода<span class="mini-preview-wrapper" style="width: 320px; height: 458px; top: -462px;"><span class="mini-preview-loading" style="height: 446px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/Nonmetals/O/O.jpg"><span class="p"><strong class="word">Кислород</strong> — химический элемент 16-й группы, второго периода периодической системы, с атомным номером 8.Кислород — химически активный неметалл, является самым лёгким элементом из группы халькогенов.</span></span></span></a> и инертных газов) образует соответствующие хлориды.:
                    <br><strong>5Cl<sub>2</sub> + 2P → 2PCl<sub>5</sub></strong>
                    <br><strong>2S + Cl<sub>2</sub> → S<sub>2</sub>Cl<sub>2</sub></strong>
                    <br><strong>S + Cl<sub>2</sub> → SCl<sub>2</sub></strong>
                <br>На свету или при нагревании активно реагирует (иногда со взрывом) с <a href="http://www.scienchemistry.org/web/HTML/H.html" class="mini-preview-anchor">водородом<span class="mini-preview-wrapper" style="width: 320px; height: 441px; top: -445px;"><span class="mini-preview-loading" style="height: 429px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/Nonmetals/H/H.jpg"><span class="p"><strong class="word">Водород</strong> — химический элемент периодической системы с обозначением H и атомным номером 1; самый лёгкий из элементов периодической таблицы. Его одноатомная форма — самое распространённое химическое вещество во Вселенной, составляющее примерно 75 % всей барионной массы.</span></span></span></a> по радикально-цепному механизму. Смеси хлора с водородом, содержащие от 5,8 до 88,3 % водорода, взрываются при облучении с образованием хлороводорода. Смесь хлора с водородом в небольших концентрациях горит бесцветным или жёлто-зелёным пламенем. Максимальная температура водородно-хлорного пламени 2200 °C.
                <br><strong>H<sub>2</sub> + Cl<sub>2</sub> → 2HCl</strong>
                <br>С <a href="http://www.scienchemistry.org/web/HTML/O.html" class="mini-preview-anchor">кислородом<span class="mini-preview-wrapper" style="width: 320px; height: 458px; top: -462px;"><span class="mini-preview-loading" style="height: 446px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/Nonmetals/O/O.jpg"><span class="p"><strong class="word">Кислород</strong> — химический элемент 16-й группы, второго периода периодической системы, с атомным номером 8.Кислород — химически активный неметалл, является самым лёгким элементом из группы халькогенов.</span></span></span></a> хлор образует оксиды, в которых он проявляет степень окисления от +1 до +7: Cl₂O, ClO₂, Cl₂O₅, Cl₂O₇. Они имеют резкий запах, термически и фотохимически нестабильны, склонны к взрывному распаду. Напрямую хлор с кислородом не реагирует. При реакции с <a href="http://www.scienchemistry.org/web/HTML/F.html" class="mini-preview-anchor">фтором<span class="mini-preview-wrapper" style="width: 320px; height: 522px; top: -526px;"><span class="mini-preview-loading" style="height: 510px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/Nonmetals/F/F.jpg"><span class="p"><strong class="word">Фтор</strong> — химический элемент 17-й группы, второго периода периодической системы, с атомным номером 9;двухатомный газ бледно-жёлтого цвета с резким запахом. Самый химически активный неметалл и сильнейший окислитель.</span></span></span></a> образуется не хлорид, а фториды:
                <br><strong>Cl<sub>2</sub> + F<sub>2</sub> → 2ClF</strong>
                <br><strong>Cl<sub>2</sub> + 3F<sub>2</sub> → 2ClF<sub>3</sub></strong>
                <br><strong>Cl<sub>2</sub> + 5F<sub>2</sub> → 2ClF<sub>5</sub></strong>
                <br>Известны фторид хлора(I), фторид хлора(III) и фторид хлора(V) (ClF, ClF₃ и ClF₅), Могут быть синтезированы из элементов, степень окисления хлора меняется в зависимости от условий синтеза. Все они представляют собой при комнатной температуре бесцветные ядовитые тяжёлые газы с сильным раздражающим запахом. Сильные окислители, реагируют с водой и стеклом. Используются как фторирующие агенты.</p>
                <p class="font-p">Хлор вытесняет <a href="http://www.scienchemistry.org/web/HTML/Br.html" class="mini-preview-anchor">бром<span class="mini-preview-wrapper" style="width: 320px; height: 503px; top: -507px; left: -10px;"><span class="mini-preview-loading" style="height: 491px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/Nonmetals/Br/Br.jpg"><span class="p"><strong class="word">Бром</strong> — химический элемент с атомным номером 35. Принадлежит к 17-й группе периодической таблицы, находится в четвёртом периоде таблицы. Простое вещество бром при нормальных условиях является тяжёлой едкой жидкостью красно-бурого цвета с сильным неприятным «тяжёлым» запахом.</span></span></span></a> и <a href="http://www.scienchemistry.org/web/HTML/I.html" class="mini-preview-anchor">иод<span class="mini-preview-wrapper" style="width: 320px; height: 354px; top: -358px; left: -10px;"><span class="mini-preview-loading" style="height: 342px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/Nonmetals/I/I.jpg"><span class="p"><strong class="word">Иод</strong> — химический элемент с атомным номером 53. Принадлежит к 17-й группе периодической таблицы химических элементов, находится в пятом периоде таблицы.</span></span></span></a> из их соединений с водородом и металлами:
                    <br><strong>Cl<sub>2</sub> + 2HBr → Br<sub>2</sub> + 2HCl</strong>
                    <br><strong>Cl<sub>2</sub> + 2NaI → I<sub>2</sub> + 2NaCl</strong>
                <br>При реакции с монооксидом <a href="http://www.scienchemistry.org/web/HTML/C.html" class="mini-preview-anchor">углерода<span class="mini-preview-wrapper" style="width: 320px; height: 502px; top: -506px;"><span class="mini-preview-loading" style="height: 490px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/Nonmetals/C/C.jpg"><span class="p"><strong class="word">Углерод</strong> —  химический элемент, обозначающийся буквой C и имеющий атомный номер 6. Он располагается в 14-й группе периодической системы. Углерод был известен ещё в античном мире.</span></span></span></a> образуется фосген:
                   <br><strong>Cl<sub>2</sub> + CO → COCl<sub>2</sub></strong>
                <br>При растворении в воде или щелочах, хлор диспропорционирует, образуя хлорноватистую (а при нагревании хлорноватую) и соляную кислоты, либо их соли:
                    <br><strong>Cl<sub>2</sub> + H<sub>2</sub>O ⟷ HCl + HClO</strong>
                    <br><strong>Cl<sub>2</sub> + 2NaOH → NaCl + NaClO + H<sub>2</sub>O</strong>  
                    <br><strong>3Cl<sub>2</sub> + 6NaOH → 5NaCl + NaCl<sub>3</sub>O + 3H<sub>2</sub>O (при нагревании)</strong>  
                <br>Хлорированием сухого гидроксида <a href="http://www.scienchemistry.org/web/HTML/Ca.html" class="mini-preview-anchor">кальция<span class="mini-preview-wrapper" style="width: 320px; height: 434px; top: -438px; left: -10px;"><span class="mini-preview-loading" style="height: 422px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/metals/second_group/Ca/Ca.jpg"><span class="p"><strong class="word">Кальций</strong> — элемент второй группы, четвёртого периода, с атомным номером 20. Простое вещество кальций — мягкий, химически активный щёлочноземельный металл серебристо-белого цвета. Впервые получен в чистом виде Г. Дэви в 1808 году.</span></span></span></a> получают хлорную известь:
                    <br><strong>Cl<sub>2</sub> + Ca(OH)<sub>2</sub> → CaCl(OCl) + H<sub>2</sub>O</strong>
                    <br>Действием хлора на аммиак можно получить трихлорид <a href="http://www.scienchemistry.org/web/HTML/N.html" class="mini-preview-anchor">азота<span class="mini-preview-wrapper" style="width: 320px; height: 435px; top: -439px;"><span class="mini-preview-loading" style="height: 423px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/Nonmetals/N/N.jpg"><span class="p"><strong class="word">Азот</strong> — химический элемент 15-й группы, второго периода периодической системы, с атомным номером 7.Как простое вещество представляет собой двухатомный газ без цвета, вкуса и запаха.Один из самых распространённых элементов на Земле.</span></span></span></a>:                            
                    <br><strong>4NH<sub>3</sub> + 3Cl<sub>2</sub> → NCl<sub>3</sub> + 3NH<sub>4</sub>Cl</strong> 
                <br>Хлор — очень сильный окислитель:
                    <br><strong>Cl<sub>2</sub> + H<sub>2</sub>S → 2HCl + S</strong>
                <br>Раствор хлора в воде используется для отбеливания тканей и бумаги.</p>   
                <p class="font-p">С насыщенными соединениями:
                    <br><strong>CH<sub>3</sub>-CH<sub>3</sub> + Cl₂ → C<sub>2</sub>H<sub>5</sub>Cl + HCl</strong>
                    <br><strong>CH<sub>4</sub> + Cl<sub>2</sub> → CH<sub>3</sub>Cl + HCl (получение хлороформа, реакция идет многоступенчато с образованием тетрахлорметана CCl<sub>4</sub> )</strong>
                <br>Присоединяется к ненасыщенным соединениям по кратным связям:
                   <br><strong>CH<sub>2</sub>=CH<sub>2</sub> + Cl<sub>2</sub> → Cl-CH<sub>2</sub>-CH<sub>2</sub>-Cl</strong>
                <br>Ароматические соединения замещают атом <a href="http://www.scienchemistry.org/web/HTML/H.html" class="mini-preview-anchor">водорода<span class="mini-preview-wrapper" style="width: 320px; height: 441px; top: -445px;"><span class="mini-preview-loading" style="height: 429px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/Nonmetals/H/H.jpg"><span class="p"><strong class="word">Водород</strong> — химический элемент периодической системы с обозначением H и атомным номером 1; самый лёгкий из элементов периодической таблицы. Его одноатомная форма — самое распространённое химическое вещество во Вселенной, составляющее примерно 75 % всей барионной массы.</span></span></span></a> на хлор в присутствии катализаторов (например, AlCl<sub>3</sub> или FeCl<sub>3</sub> ):
                    <br><strong>C<sub>6</sub>H<sub>6</sub> + Cl<sub>2</sub> → C<sub>5</sub>H<sub>5</sub>Cl + HCl</strong></p>
                <h3>Изотопы</h3>
                <p class="font-p">В природе встречаются 2 стабильных изотопа хлора: с массовым числом 35 и 37. Доли их содержания соответственно равны 75,78 % и 24,22 %.</p>              
                <h2  class="elements" >Историческая справка</h2>
                <p class="font-p">Соединение с водородом — газообразный хлороводород — был впервые получен <a href="http://www.scienchemistry.org/web/HistoricalFigures/Joseph Priestley.html" class="mini-preview-anchor">Джозеф Пристли<span class="mini-preview-wrapper" style="width: 320px; height: 507px; top: -511px; left: -10px;"><span class="mini-preview-loading" style="height: 495px;"><img class="mini-preview-img" src="http://chemistry.com/HistoricalFigures/Joseph Priestley/img2.jpg"><span class="p"><strong class="word">Джозеф Пристли</strong> — британский священник-диссентер, философ. Вошёл в историю, прежде всего, как выдающийся химик, открывший кислород.Член Лондонского королевского общества (1766), иностранный почётный член Петербургской академии наук (1780)</span></span></span></a> в 1772 г. Хлор был получен в 1774 г. шведским химиком <a href="http://www.scienchemistry.org/web/HistoricalFigures/Carl Wilhelm Scheele.html" class="mini-preview-anchor">Карлом Вильгельмом Шееле<span class="mini-preview-wrapper" style="width: 320px; height: 443px; top: -447px; left: -10px;"><span class="mini-preview-loading" style="height: 431px;"><img class="mini-preview-img" src="http://chemistry.com/HistoricalFigures/Carl Wilhelm Scheele/img.jpg"><span class="p"><strong class="word">Карл Вильгельм Шееле</strong> — шведский химик-фармацевт. Он выделил и исследовал множество химических соединений, а также стал первооткрывателем нескольких химических элементов, в частности, кислорода.</span></span></span></a>, описавшим его выделение при взаимодействии пиролюзита с соляной кислотой в своём трактате о пиролюзите:
                    <br><strong>4HCl + MnO<sub>2</sub> → MnCl<sub>2</sub> + Cl<sub>2</sub>↑ +H<sub>2</sub>O</strong>
                <br>Шееле отметил запах хлора, схожий с запахом царской водки, его способность взаимодействовать с <a href="http://www.scienchemistry.org/web/HTML/Au.html" class="mini-preview-anchor">золотом<span class="mini-preview-wrapper" style="width: 320px; height: 444px; top: -448px; left: -10px;"><span class="mini-preview-loading" style="height: 432px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/metals/nine_row/Au/Au.jpg"><span class="p"><strong class="word">Золото</strong> — химический элемент 11 группы, шестого периода периодической системы химических элементов, с атомным номером 79. Простое вещество золото — благородный металл жёлтого цвета.</span></span></span></a> и киноварью, а также его отбеливающие свойства. Однако Шееле, в соответствии с господствовавшей в химии того времени теорией флогистона, предположил, что хлор представляет собой дефлогистированную муриевую (соляную) кислоту. Бертолле и <a href="http://www.scienchemistry.org/web/HistoricalFigures/Antoine Laurent.html" class="mini-preview-anchor">Лавуазье<span class="mini-preview-wrapper" style="width: 320px; height: 448px; top: -452px; left: -10px;"><span class="mini-preview-loading" style="height: 436px;"><img class="mini-preview-img" src="http://chemistry.com/HistoricalFigures/Antoine Laurent/img2.jpg"><span class="p"><strong class="word">Антуан Лавуазье</strong> — французский естествоиспытатель, основатель современной химии.</span></span></span></a> в рамках кислородной теории кислот обосновали, что новое вещество должно быть оксидом гипотетического элемента мурия. Однако попытки его выделения оставались безуспешными вплоть до работ Г. Дэви, которому электролизом удалось разложить поваренную соль на <a href="http://www.scienchemistry.org/web/HTML/Na.html" class="mini-preview-anchor">натрий<span class="mini-preview-wrapper" style="width: 320px; height: 483px; top: -487px;"><span class="mini-preview-loading" style="height: 471px;"><img class="mini-preview-img" src="http://chemistry.com/Elements/Image/metals/first_group/Na/Na.jpg"><span class="p"><strong class="word">Натрий</strong> — химический элемент первой группы, 3-го периода периодической системы, с атомным номером 11,мягкий щелочной металл серебристо-белого цвета. В свободном виде в природе не встречается. Натрий — шестой по распространённости элемент в земной коре.</span></span></span></a> и хлор, доказав элементарную природу последнего.</p>
                <p class="font-p">В 1811 г. <a href="http://www.scienchemistry.org/web/HistoricalFigures/Humphry Davy.html" class="mini-preview-anchor">Дэви<span class="mini-preview-wrapper" style="width: 320px; height: 472px; top: -476px;"><span class="mini-preview-loading" style="height: 460px;"><img class="mini-preview-img" src="http://chemistry.com/HistoricalFigures/Humphry Davy/img2.jpg"><span class="p"><strong class="word">Гемфри Дэви</strong> — британский химик, агрохимик, физик и геолог, изобретатель, один из основателей электрохимии. Известен открытием многих химических элементов, а также покровительством Фарадею на начальном этапе его научной деятельности.</span></span></span></a> предложил для нового элемента название «хлорин» (chlorine). Спустя год Ж. Гей-Люссак «сократил» название до хлора (chlore). В том же 1811 г. немецкий физик Иоганн Швейгер предложил для хлора название «галоген» (дословно солерод), однако впоследствии этот термин закрепился за всей 17-й (VIIA) группой элементов, в которую входит и хлор.</p>
                <p class="font-p">В 1826 году атомная масса хлора была с высокой точностью определена шведским химиком <a href="http://www.scienchemistry.org/web/HistoricalFigures/Jakob Berzelius.html" class="mini-preview-anchor">Йёнсом Якобсом Берцелиусом<span class="mini-preview-wrapper" style="width: 320px; height: 492px; top: -501px; left: -10px;"><span class="mini-preview-loading" style="height: 480px;"><img class="mini-preview-img" src="http://chemistry.com/HistoricalFigures/Jakob Berzelius/img.jpg"><span class="p"><strong class="word">Йёнс Берцелиус</strong> — шведский химик и минералог.Ввёл современные символы химических элементов. Открыл церий, селен и торий. Развил электрохимическую теорию. Предложил термины аллотропия, изомерия, катализ и другие.</span></span></span></a> (отличается от современных данных не более, чем на 0,1 %).</p>
            </div>
        </div>
    </div>
</body>
</html> 